import type { Asset, Incident, SecurityEvent, CommandSummaryData } from "@/lib/types";

const isDev = process.env.NODE_ENV === "development";

export const demoAssets: Asset[] = [
  {
    id: 1,
    asset_uid: "FS-ASSET-001",
    hostname: "PLC-PRESS-04",
    ip_address: "192.168.40.22",
    mac_address: "00:1B:1C:0A:44:91",
    site: "Detroit Forge Line 2",
    segment: "Production",
    asset_type: "plc",
    authorization_state: "authorized",
    owner: "OT Engineering",
    status: "Online",
    first_seen: "2025-11-18T08:11:31Z",
    last_seen: "2026-04-27T14:06:10Z",
    open_ports: [
      { port: 502, service: "Modbus", risk: "high" },
      { port: 80, service: "HTTP", risk: "medium" },
    ],
    metadata: { os_version: "v2.4.1" },
    created_at: "2025-11-18T08:11:31Z",
    updated_at: "2026-04-27T14:06:10Z",
    risk_score: 78,
    risk_level: "high",
  },
  {
    id: 2,
    asset_uid: "FS-ASSET-002",
    hostname: "UNKNOWN-LAPTOP-17",
    ip_address: "192.168.40.105",
    mac_address: "7C:8A:E1:44:19:AF",
    site: "Detroit Forge Line 2",
    segment: "Production",
    asset_type: "laptop",
    authorization_state: "unauthorized",
    owner: "Unverified",
    status: "Online",
    first_seen: "2026-04-27T13:41:05Z",
    last_seen: "2026-04-27T14:08:22Z",
    open_ports: [
      { port: 445, service: "SMB", risk: "high" },
      { port: 3389, service: "RDP", risk: "critical" },
      { port: 135, service: "RPC", risk: "high" },
    ],
    metadata: { os_version: "Windows 10" },
    created_at: "2026-04-27T13:41:05Z",
    updated_at: "2026-04-27T14:08:22Z",
    risk_score: 100,
    risk_level: "critical",
  },
  {
    id: 3,
    asset_uid: "FS-ASSET-003",
    hostname: "HMI-LINE2-07",
    ip_address: "192.168.40.37",
    mac_address: "4A:11:7D:EE:29:10",
    site: "Detroit Forge Line 2",
    segment: "Production",
    asset_type: "workstation",
    authorization_state: "authorized",
    owner: "Line Operations",
    status: "Online",
    first_seen: "2024-08-03T10:20:00Z",
    last_seen: "2026-04-27T14:03:40Z",
    open_ports: [
      { port: 5900, service: "VNC", risk: "critical" },
      { port: 443, service: "HTTPS", risk: "low" },
    ],
    metadata: { os_version: "HMI Runtime v3.1" },
    created_at: "2024-08-03T10:20:00Z",
    updated_at: "2026-04-27T14:03:40Z",
    risk_score: 58,
    risk_level: "medium",
  },
  {
    id: 4,
    asset_uid: "FS-ASSET-004",
    hostname: "SRV-HISTORIAN-01",
    ip_address: "10.20.4.18",
    mac_address: "1E:9C:22:F1:42:0B",
    site: "Detroit Forge",
    segment: "Servers",
    asset_type: "server",
    authorization_state: "authorized",
    owner: "Manufacturing Data",
    status: "Online",
    first_seen: "2023-04-14T12:05:11Z",
    last_seen: "2026-04-27T14:02:15Z",
    open_ports: [
      { port: 443, service: "HTTPS", risk: "low" },
      { port: 1433, service: "MSSQL", risk: "high" },
    ],
    metadata: { os_version: "Windows Server 2019" },
    created_at: "2023-04-14T12:05:11Z",
    updated_at: "2026-04-27T14:02:15Z",
    risk_score: 42,
    risk_level: "medium",
  },
  {
    id: 5,
    asset_uid: "FS-ASSET-005",
    hostname: "PRN-LABEL-03",
    ip_address: "192.168.55.43",
    mac_address: "A0:CE:C8:14:60:B2",
    site: "Detroit Forge",
    segment: "Printers/IoT",
    asset_type: "printer",
    authorization_state: "unknown",
    owner: "Shipping",
    status: "Online",
    first_seen: "2026-04-20T09:00:15Z",
    last_seen: "2026-04-27T13:58:02Z",
    open_ports: [
      { port: 9100, service: "JetDirect", risk: "medium" },
      { port: 80, service: "HTTP", risk: "low" },
    ],
    metadata: { os_version: "JetDirect 7.2" },
    created_at: "2026-04-20T09:00:15Z",
    updated_at: "2026-04-27T13:58:02Z",
    risk_score: 28,
    risk_level: "low",
  },
  {
    id: 6,
    asset_uid: "FS-ASSET-006",
    hostname: "ENG-WS-12",
    ip_address: "10.20.8.52",
    mac_address: "D4:6A:6A:99:12:10",
    site: "Detroit Forge",
    segment: "Corporate",
    asset_type: "workstation",
    authorization_state: "authorized",
    owner: "Controls Engineering",
    status: "Online",
    first_seen: "2024-02-11T08:18:19Z",
    last_seen: "2026-04-27T14:01:55Z",
    open_ports: [{ port: 443, service: "Agent", risk: "low" }],
    metadata: { os_version: "Windows 11" },
    created_at: "2024-02-11T08:18:19Z",
    updated_at: "2026-04-27T14:01:55Z",
    risk_score: 12,
    risk_level: "low",
  },
];

export const demoIncidents: Incident[] = [
  {
    id: 1,
    incident_uid: "INC-2404-001",
    title: "Unauthorized contractor laptop exposing SMB/RDP on production segment",
    summary:
      "ForgeSentinel correlated a newly observed unauthorized laptop with remote access exposure on the production segment. Lateral movement risk is elevated because SMB and RDP are reachable from the same cell network as PLC-PRESS-04.",
    severity: "critical",
    status: "Investigating",
    risk_score: 100,
    confidence_score: 94,
    category: "Unauthorized Asset",
    first_observed_at: "2026-04-27T13:41:05Z",
    last_observed_at: "2026-04-27T14:08:22Z",
    assigned_to: "SOC Analyst",
    resolution_notes: "",
    affected_assets: ["UNKNOWN-LAPTOP-17", "PLC-PRESS-04"],
    timeline: [
      { time: "13:41:05", actor: "demo scanner", event: "Observation captured", summary: "MAC 7C:8A:E1:44:19:AF appeared on production VLAN." },
      { time: "13:43:18", actor: "service probe", event: "Ports detected", summary: "SMB, RPC, and RDP accepted TCP connections." },
      { time: "13:44:02", actor: "risk engine", event: "Risk decision generated", summary: "Score 100 critical from unauthorized status and remote services." },
      { time: "13:45:30", actor: "correlator", event: "Incident correlated", summary: "Linked contractor laptop with PLC exposure in same segment." },
    ],
    recommendations: [
      {
        id: 1,
        incident_id: 1,
        rank: 1,
        action_type: "isolate",
        action_label: "Isolate asset at switch port",
        rationale: "The device is unauthorized and exposes remote access services inside production.",
        expected_benefit: "Stops lateral movement path while preserving evidence.",
        confidence: 96,
        requires_approval: true,
        status: "pending",
        created_at: "2026-04-27T13:45:30Z",
        updated_at: "2026-04-27T13:45:30Z",
      },
      {
        id: 2,
        incident_id: 1,
        rank: 2,
        action_type: "verify",
        action_label: "Verify owner and maintenance window",
        rationale: "Contractor activity may be legitimate but must be reconciled before restoration.",
        expected_benefit: "Reduces false-positive closure and improves asset registry.",
        confidence: 88,
        requires_approval: false,
        status: "pending",
        created_at: "2026-04-27T13:45:30Z",
        updated_at: "2026-04-27T13:45:30Z",
      },
    ],
    decision_trace: [
      { label: "Unauthorized asset", value: 35 },
      { label: "Production segment", value: 20 },
      { label: "RDP exposed", value: 18 },
      { label: "SMB exposed", value: 12 },
      { label: "New since last scan", value: 7 },
    ],
    notes: ["Awaiting OT supervisor confirmation.", "Switch port candidate: SW-FORGE-02 gi1/0/17."],
    aether_ticket_id: null,
    aether_ticket_url: null,
    aether_sync_status: "pending",
  },
  {
    id: 2,
    incident_uid: "INC-2404-002",
    title: "Remote access exposure detected on HMI workstation",
    summary: "VNC is reachable on an authorized HMI. The service creates process visibility and remote-control risk.",
    severity: "high",
    status: "Open",
    risk_score: 58,
    confidence_score: 89,
    category: "Remote Access",
    first_observed_at: "2026-04-27T12:12:20Z",
    last_observed_at: "2026-04-27T12:13:07Z",
    assigned_to: "SOC Analyst",
    resolution_notes: "",
    affected_assets: ["HMI-LINE2-07"],
    timeline: [
      { time: "12:12:20", actor: "scan sensor", event: "Service observed", summary: "VNC handshake detected on tcp/5900." },
      { time: "12:13:07", actor: "risk engine", event: "Risk recomputed", summary: "HMI remote-control feature elevated score to 58." },
    ],
    recommendations: [
      {
        id: 3,
        incident_id: 2,
        rank: 1,
        action_type: "restrict",
        action_label: "Restrict VNC to jump host",
        rationale: "Remote control should never be broadly reachable inside production.",
        expected_benefit: "Reduces unauthorized operator access path.",
        confidence: 90,
        requires_approval: true,
        status: "pending",
        created_at: "2026-04-27T12:13:07Z",
        updated_at: "2026-04-27T12:13:07Z",
      },
    ],
    decision_trace: [
      { label: "HMI asset", value: 18 },
      { label: "VNC exposed", value: 28 },
      { label: "Production segment", value: 20 },
    ],
    notes: ["No active session observed."],
    aether_ticket_id: null,
    aether_ticket_url: null,
    aether_sync_status: "pending",
  },
];

export const demoEvents: SecurityEvent[] = [
  {
    id: 1,
    event_uid: "EVT-240427-001",
    event_type: "Risk decision",
    severity: "critical",
    asset_id: 2,
    incident_id: 1,
    source: "risk-engine",
    description: "Critical risk 100 written to asset record.",
    payload: {},
    observed_at: "2026-04-27T14:08:22Z",
    created_at: "2026-04-27T14:08:22Z",
  },
  {
    id: 2,
    event_uid: "EVT-240427-002",
    event_type: "Recommendation",
    severity: "high",
    asset_id: 1,
    incident_id: 1,
    source: "recommendation-engine",
    description: "Isolate asset ranked as primary response.",
    payload: {},
    observed_at: "2026-04-27T14:07:41Z",
    created_at: "2026-04-27T14:07:41Z",
  },
  {
    id: 3,
    event_uid: "EVT-240427-003",
    event_type: "Exposure",
    severity: "high",
    asset_id: 1,
    source: "scan-sensor",
    description: "Modbus reachable from production scan sensor.",
    payload: {},
    observed_at: "2026-04-27T14:06:10Z",
    created_at: "2026-04-27T14:06:10Z",
  },
  {
    id: 4,
    event_uid: "EVT-240427-004",
    event_type: "Telemetry",
    severity: "medium",
    asset_id: 4,
    source: "scan-sensor",
    description: "MSSQL exposure scope changed.",
    payload: {},
    observed_at: "2026-04-27T14:03:40Z",
    created_at: "2026-04-27T14:03:40Z",
  },
  {
    id: 5,
    event_uid: "EVT-240427-005",
    event_type: "Identity",
    severity: "medium",
    asset_id: 5,
    source: "identity-resolver",
    description: "Authorization remains unknown.",
    payload: {},
    observed_at: "2026-04-27T13:58:02Z",
    created_at: "2026-04-27T13:58:02Z",
  },
];

export const demoKpis: CommandSummaryData = {
  highest_risk_incident: {
    id: 1,
    incident_uid: "INC-2404-001",
    title: "Unauthorized contractor laptop exposing SMB/RDP on production segment",
    severity: "critical",
    risk_score: 100,
    category: "Unauthorized Asset",
    affected_assets: ["UNKNOWN-LAPTOP-17", "PLC-PRESS-04"],
  },
  recommended_action: "Isolate asset at switch port SW-FORGE-02 gi1/0/17",
  data_freshness: "Live",
  kpis: {
    total_assets: 6,
    critical_count: 1,
    high_count: 1,
    medium_count: 2,
    low_count: 2,
    unauthorized_count: 1,
    unknown_count: 1,
    open_incidents: 2,
    active_scans: 0,
    last_scan_at: "2026-04-27T14:08:22Z",
  },
};

export function withDemoData<T>(realData: T | undefined, demoFallback: T): T {
  if (!isDev) return realData ?? demoFallback;
  if (realData === undefined || realData === null) return demoFallback;
  // If it's an array and empty, return demo
  if (Array.isArray(realData) && realData.length === 0) return demoFallback;
  // If it's an object with an items array and it's empty, merge demo
  if (typeof realData === "object" && realData !== null && "items" in realData) {
    const items = (realData as any).items;
    if (Array.isArray(items) && items.length === 0) {
      return { ...realData, items: (demoFallback as any).items };
    }
  }
  return realData;
}
